# Sentinel Common Data Model

```{r setup, include=FALSE}
# set chunks defaults
knitr::opts_chunk$set(
  echo       = FALSE,
  message    = FALSE,
  warning    = FALSE
)

options(knitr.kable.NA = '')
options(kableExtra.html.bsTable = T)

library(jsonlite)
library(dplyr)
library(purrr)
library(magrittr)
library(tidyr)

source("./R/functions.R")

print_dd <- function(name, abbreviation, description, unique_row, sort_order, variables) {

  cat('## ', abbreviation, "\n\n")
  cat('### ', name, "\n\n")
  cat(description, "\n\n")
  cat("<b>Unique Row</b>: ", unique_row, "\n\n")
  cat("<b>Sort Order</b>: ", sort_order, "\n\n")
  cat("\n")
  cat("\n")


.attributes <- variables %>%
    dplyr::mutate(dplyr::across(everything(), ~ purrr::map(.x, ~ ifelse(is.null(.x), NA, .x)))) %>%
    dplyr::select(-notes) %>%
    dplyr::relocate(missing_allowed, .after = values) %>%
    dplyr::relocate(example, .after = guidance) %>%
    dplyr::rename(`Variable Name` = variable_name,
                  `Variable Type and Length (Bytes)` = var_type_length,
                  `Values` =  values,
                  `Missing Values Allowed?` = missing_allowed,
                  Definition = definition,
                  Example = example,
                  Guidance = guidance)

  # .notes <- variables %>%
  #   dplyr::pull(notes) %>%
  #   unlist() %>%
  #   purrr::discard(is.na) %>%
  #   unique()

    cat(kableExtra::kbl(.attributes,
                      "html",
                      escape = FALSE
  ) %>%
    kableExtra::column_spec(7, monospace = TRUE) %>%
    kableExtra::kable_styling(
      full_width = TRUE,
      fixed_thead = FALSE,
      bootstrap_options = c("responsive", "striped"),
      "\n"
    ) 
  )
  cat("\n")
  cat("\n")
}

scdm <- fromJSON("./data/scdm.json")

tables <- scdm %>%
  purrr::pluck("tables") %>%
  json_to_html()
```


:::{.panel-tabset}

```{r, echo=FALSE, results="asis"}
purrr::pwalk(.l=list(tables$table_name, tables$abbreviation, tables$description, tables$unique_row, tables$sort_order, tables$variables), .f=print_dd)
```

:::